/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.its.lf;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author lorenz
 */
public class GUI_Adressverwaltung_DB extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Adressverwaltung_DB
     */
    public GUI_Adressverwaltung_DB() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta_daten = new javax.swing.JTextArea();
        bt_loadData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta_daten.setColumns(20);
        ta_daten.setRows(5);
        jScrollPane1.setViewportView(ta_daten);

        bt_loadData.setText("Daten einlesen");
        bt_loadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_loadDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(bt_loadData)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(bt_loadData)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_loadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_loadDataActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        Statement stat = null;
        ResultSet rs = null;

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            ta_daten.setText("Fehler: " + ex.getMessage());

        }

        try {
            con = DriverManager.getConnection("jdbc:mysql://10.201.9.202:3306/sakila", "lorenz", "lorenz123");
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Adressverwaltung_DB.class.getName()).log(Level.SEVERE, null, ex);
            ta_daten.setText("Fehler: " + ex.getMessage());
        }

        try {
            stat = con.createStatement(); //Statement erzeugen
            stat.executeQuery("SELECT * from film;");
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Adressverwaltung_DB.class.getName()).log(Level.SEVERE, null, ex);
            ta_daten.setText("Fehler: " + ex.getMessage());
        }

        try {
            rs = stat.getResultSet();
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Adressverwaltung_DB.class.getName()).log(Level.SEVERE, null, ex);
            ta_daten.setText("Fehler: " + ex.getMessage());
        }

        try {
            while (rs.next()) { //DAten verarbeiten
                for (int i = 1; i <= rs.getMetaData().getColumnCount(); i++) {
                    ta_daten.append(rs.getString(i) + "\n");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(GUI_Adressverwaltung_DB.class.getName()).log(Level.SEVERE, null, ex);
            ta_daten.setText("Fehler: " + ex.getMessage());
        }
        try { // Resultset schließen
            rs.close();
        } catch (SQLException ex) {
            ta_daten.setText("Fehler: " + ex.getMessage());
        }
        try { // Statement schließen
            stat.close();
        } catch (SQLException ex) {
            ta_daten.setText("Fehler: " + ex.getMessage());
        }
        try { // Verbindung schließen
            con.close();
        } catch (SQLException ex) {
            ta_daten.setText("Fehler: " + ex.getMessage());
        }
    }//GEN-LAST:event_bt_loadDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Adressverwaltung_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Adressverwaltung_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Adressverwaltung_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Adressverwaltung_DB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Adressverwaltung_DB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_loadData;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_daten;
    // End of variables declaration//GEN-END:variables
}
