/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.its.lf;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author lorenz
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    ArrayList<Mitglied> mitglieder = new ArrayList<>();
    int i;

    public GUI() {
        initComponents();
        sperren();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_activepassive = new javax.swing.JComboBox<>();
        txf_name = new javax.swing.JTextField();
        txf_sportart1 = new javax.swing.JTextField();
        txf_sportart2 = new javax.swing.JTextField();
        txf_spendenhoehe = new javax.swing.JTextField();
        bt_erfassen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        bt_anzeigen = new javax.swing.JButton();
        cb_selectname = new javax.swing.JComboBox<>();
        txf_selectedname = new javax.swing.JTextField();
        bt_changename = new javax.swing.JButton();
        bt_sortnames = new javax.swing.JButton();
        bt_sortdesc = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cb_activepassive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aktives mitglied", "passives mitglied" }));
        cb_activepassive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_activepassiveActionPerformed(evt);
            }
        });

        txf_name.setText("jTextField1");

        txf_sportart1.setText("jTextField1");

        txf_sportart2.setText("jTextField1");

        txf_spendenhoehe.setText("jTextField1");

        bt_erfassen.setText("erfassen");
        bt_erfassen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_erfassenActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        bt_anzeigen.setText("Mitglieder anzeigen");

        cb_selectname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txf_selectedname.setText("jTextField1");

        bt_changename.setText("name ändern");
        bt_changename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_changenameActionPerformed(evt);
            }
        });

        bt_sortnames.setText("sortieren");
        bt_sortnames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sortnamesActionPerformed(evt);
            }
        });

        bt_sortdesc.setText("absteigend");
        bt_sortdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sortdescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_anzeigen)
                        .addGap(27, 27, 27)
                        .addComponent(bt_sortnames)
                        .addGap(38, 38, 38)
                        .addComponent(bt_sortdesc)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txf_spendenhoehe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txf_sportart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_activepassive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cb_selectname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txf_sportart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(txf_selectedname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(98, 98, 98)
                                        .addComponent(bt_changename))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addComponent(bt_erfassen)))))
                        .addContainerGap(154, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cb_activepassive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_spendenhoehe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txf_sportart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_sportart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_erfassen))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_selectname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_selectedname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_changename))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_anzeigen)
                    .addComponent(bt_sortnames)
                    .addComponent(bt_sortdesc))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_erfassenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_erfassenActionPerformed
        // TODO add your handling code here:

        if (cb_activepassive.getSelectedIndex() == 0) {

            Mitglied mitglied = new aktiv(txf_sportart1.getText(), txf_sportart2.getText(), i, txf_name.getText());
            mitglieder.add(mitglied);
        } else {
            Mitglied mitglied = new passiv(Double.valueOf(txf_spendenhoehe.getText()), i, txf_name.getText());
            mitglieder.add(mitglied);
        }

        i++;
        jList1.setListData(mitglieder.toArray());
        
        String[] names = new String[mitglieder.toArray().length];

        for (int j = 0; j < mitglieder.toArray().length; j++) {
            names[j] = mitglieder.get(j).getName();

        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(names);

        cb_selectname.setModel(model);
    }//GEN-LAST:event_bt_erfassenActionPerformed
    private void sperren() {
        if (cb_activepassive.getSelectedIndex() == 0) {
            txf_spendenhoehe.setEnabled(false);
            txf_sportart1.setEnabled(true);
            txf_sportart2.setEnabled(true);
        } else {
            txf_sportart1.setEnabled(false);
            txf_sportart2.setEnabled(false);
            txf_spendenhoehe.setEnabled(true);
        }
    }
    private void cb_activepassiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_activepassiveActionPerformed
        // TODO add your handling code here:
        sperren();
    }//GEN-LAST:event_cb_activepassiveActionPerformed

    private void bt_changenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_changenameActionPerformed
        // TODO add your handling code here:
        Mitglied mitglied = mitglieder.get(cb_selectname.getSelectedIndex());
        mitglied.setName(txf_selectedname.getText());
        jList1.setListData(mitglieder.toArray());
        String[] names = new String[mitglieder.toArray().length];

        for (int j = 0; j < mitglieder.toArray().length; j++) {
            names[j] = mitglieder.get(j).getName();

        }
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(names);

        cb_selectname.setModel(model);

    }//GEN-LAST:event_bt_changenameActionPerformed

    private void bt_sortnamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sortnamesActionPerformed
        // TODO add your handling code here:
        NameComperator NameComperator = new NameComperator(Sortdirection.ASCEND);
        mitglieder.sort(NameComperator);

        jList1.setListData(mitglieder.toArray());
    }//GEN-LAST:event_bt_sortnamesActionPerformed

    private void bt_sortdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sortdescActionPerformed
        // TODO add your handling code here:
        NameComperator NameComperator = new NameComperator(Sortdirection.DESCEND);
        mitglieder.sort(NameComperator);

        jList1.setListData(mitglieder.toArray());
    }//GEN-LAST:event_bt_sortdescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_anzeigen;
    private javax.swing.JButton bt_changename;
    private javax.swing.JButton bt_erfassen;
    private javax.swing.JButton bt_sortdesc;
    private javax.swing.JButton bt_sortnames;
    private javax.swing.JComboBox<String> cb_activepassive;
    private javax.swing.JComboBox<String> cb_selectname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txf_name;
    private javax.swing.JTextField txf_selectedname;
    private javax.swing.JTextField txf_spendenhoehe;
    private javax.swing.JTextField txf_sportart1;
    private javax.swing.JTextField txf_sportart2;
    // End of variables declaration//GEN-END:variables
}
