package de.its.lf;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import de.its.lf.PersonenTableModel;

public class GUI extends javax.swing.JFrame {

    //PersonenListe Liste = new PersonenListeFile(file);
    /**
     * Creates new form GUI
     */
    private PersonenListe liste;
    private PersonenTableModel personenTableModel;

    public GUI() throws SQLException {
        initComponents();
        initData();
    }

    private void initData() throws SQLException {
        DBConnector dbConnect = new DBConnectorMySQL("10.201.9.202", 3306, "lorenz", "lorenz123", "sakila");
        liste = new PersonenListeDB(dbConnect);
        //liste = new PersonenListeFile(new File("C:\\Users\\loren\\OneDrive - it.schule stuttgart\\GitHub\\GitHub_Softwareentwicklung\\Interfaces\\Adressverwaltung_int\\Adressen.csv"));
        JOptionPane.showMessageDialog(this, "Der Import der Daten hat erfolgreich funktioniert", "", JOptionPane.INFORMATION_MESSAGE);
        personenTableModel = new PersonenTableModel(liste.getListe());
        tblPersonen.setModel(personenTableModel);

        //jList1.setListData(liste.get());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txf_firstName = new javax.swing.JTextField();
        txf_lastName = new javax.swing.JTextField();
        txf_eMail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bt_aendern = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_add = new javax.swing.JButton();
        bt_sortLastName = new javax.swing.JButton();
        bt_sortFirstName = new javax.swing.JButton();
        box_lastNameSort = new javax.swing.JComboBox<>();
        box_firstNamesort = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPersonen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vorname");

        jLabel2.setText("Nachname");

        jLabel7.setText("E-Mail");

        bt_aendern.setText("ändern");
        bt_aendern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_aendernActionPerformed(evt);
            }
        });

        bt_delete.setText("löschen");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });

        bt_add.setText("Datensatz hinzufügen");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_sortLastName.setText("sort Nachname");
        bt_sortLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sortLastNameActionPerformed(evt);
            }
        });

        bt_sortFirstName.setText("sort Vorname");
        bt_sortFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_sortFirstNameActionPerformed(evt);
            }
        });

        box_lastNameSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aufsteigend", "absteigend" }));
        box_lastNameSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_lastNameSortActionPerformed(evt);
            }
        });

        box_firstNamesort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "aufsteigend", "absteigend" }));

        tblPersonen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tblPersonen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonenMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPersonen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 989, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(33, 33, 33)
                            .addComponent(txf_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                            .addComponent(txf_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txf_eMail, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(box_lastNameSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(box_firstNamesort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bt_aendern, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_sortLastName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_sortFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txf_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txf_eMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(159, 159, 159)
                        .addComponent(bt_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_aendern)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_sortLastName)
                            .addComponent(box_lastNameSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_sortFirstName)
                            .addComponent(box_firstNamesort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_aendernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_aendernActionPerformed

        int index = tblPersonen.getSelectedRow();

        Person person = liste.getListe().get(index);

        if (person != null) {
            //  System.out.println(txf_firstName.getText());
            person.setFirstName(txf_firstName.getText());
            person.setLastName(txf_lastName.getText());

            person.setEmail(txf_eMail.getText());

            try {
                liste.update(person);
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            //jList1.setListData(liste.get());
            // tblPersonen.setModel(new PersonenTableModel(liste.getListe())); --> unnötig
            tblPersonen.repaint(); //reicht!
        }


    }//GEN-LAST:event_bt_aendernActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            int index = tblPersonen.getSelectedRow();
            Person person = liste.getListe().get(index);
            liste.delete(person);
            //jList1.setListData(liste.get());
            //tblPersonen.setModel(new PersonenTableModel(liste.getListe()));
            tblPersonen.repaint(); //reicht!
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Fehler beim Löschen");
        }
    }//GEN-LAST:event_bt_deleteActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        //hier könnte man noch abfragen, ob ALLE felder 0 sind weil dort wird aktuell noch eine Fehlermeldung geworfen
        try {
            Person person = new Person();
            person.setFirstName(txf_firstName.getText());
            person.setLastName(txf_lastName.getText());

            person.setEmail(txf_eMail.getText());

            liste.insert(person);
            //jList1.setListData(liste.get());
            //tblPersonen.setModel(new PersonenTableModel(liste.getListe()));
            tblPersonen.repaint(); //reicht!

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Falsche Eingabe");
        }
    }//GEN-LAST:event_bt_addActionPerformed

    private void bt_sortLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sortLastNameActionPerformed
        // TODO add your handling code here:
        if (box_lastNameSort.getSelectedIndex() == 0) {
            liste.sortLastname(SortDirection.ASCEND);
        } else {
            liste.sortLastname(SortDirection.DESCEND);
        }
        //jList1.setListData(liste.get());
        //tblPersonen.setModel(new PersonenTableModel(liste.getListe()));
        tblPersonen.repaint(); //reicht!
    }//GEN-LAST:event_bt_sortLastNameActionPerformed

    private void bt_sortFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_sortFirstNameActionPerformed
        // TODO add your handling code here:
        if (box_firstNamesort.getSelectedIndex() == 0) {
            liste.sortFirstname(SortDirection.ASCEND);
        } else {
            liste.sortFirstname(SortDirection.DESCEND);
        }
        //jList1.setListData(liste.get());
        //tblPersonen.setModel(new PersonenTableModel(liste.getListe()));
        tblPersonen.repaint(); //reicht!
    }//GEN-LAST:event_bt_sortFirstNameActionPerformed

    private void tblPersonenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonenMouseClicked
        // TODO add your handling code here:
        int index = tblPersonen.getSelectedRow();
        //Person person = (Person) tblPersonen.getSelectedRow();
        Person person = liste.getListe().get(index);
        if (person != null) {
            txf_firstName.setText(person.getFirstName());
            txf_lastName.setText(person.getLastName());
            txf_eMail.setText(person.getEmail());

        }
    }//GEN-LAST:event_tblPersonenMouseClicked

    private void box_lastNameSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_lastNameSortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_lastNameSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GUI().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box_firstNamesort;
    private javax.swing.JComboBox<String> box_lastNameSort;
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_aendern;
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_sortFirstName;
    private javax.swing.JButton bt_sortLastName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblPersonen;
    private javax.swing.JTextField txf_eMail;
    private javax.swing.JTextField txf_firstName;
    private javax.swing.JTextField txf_lastName;
    // End of variables declaration//GEN-END:variables
}
