/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.its.lf;

/**
 *
 * @author lorenz
 */
public class gui_main extends javax.swing.JFrame {

    /**
     * Creates new form gui_main
     */
    public gui_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_ueberschrift = new javax.swing.JLabel();
        bt_m_in_e = new javax.swing.JButton();
        lb_Startmeter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txf_startmeter = new javax.swing.JTextField();
        txf_endmeter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_e_in_m = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txa_ausgabe = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_ueberschrift.setText("Wie möchten Sie umrechnen?");

        bt_m_in_e.setText("metrisch in englisch");
        bt_m_in_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_m_in_eActionPerformed(evt);
            }
        });

        lb_Startmeter.setText("Startmeter");

        jLabel1.setText("Endmeter");

        jLabel2.setText("Bitte geben Sie den Start und Endmeter ein:");

        bt_e_in_m.setText("englisch in metrisch");
        bt_e_in_m.setToolTipText("");
        bt_e_in_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_e_in_mActionPerformed(evt);
            }
        });

        txa_ausgabe.setColumns(20);
        txa_ausgabe.setRows(5);
        jScrollPane1.setViewportView(txa_ausgabe);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_m_in_e)
                            .addComponent(lb_ueberschrift)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_Startmeter)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txf_endmeter, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                    .addComponent(txf_startmeter)))
                            .addComponent(jLabel2)
                            .addComponent(bt_e_in_m))
                        .addGap(0, 46, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_Startmeter)
                    .addComponent(txf_startmeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txf_endmeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_ueberschrift)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_m_in_e)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_e_in_m)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_m_in_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_m_in_eActionPerformed
        // TODO add your handling code here:
        double startmeter, endmeter, yard, inch, feet;

        String ausgabe = "meter:   inch:     feet:     yard:";
        startmeter = Double.parseDouble(txf_startmeter.getText());
        endmeter = Double.parseDouble(txf_endmeter.getText());

        while (startmeter <= endmeter) {

            inch = startmeter * 100 / 2.54;
            feet = startmeter / 0.3048;
            yard = startmeter / 0.9144;

            ausgabe = ausgabe + "\n" + String.format("%6.2f %8.2f %8.2f %8.2f\n", startmeter, inch, feet, yard);

            startmeter++;

        }
        txa_ausgabe.setText(ausgabe);
    }//GEN-LAST:event_bt_m_in_eActionPerformed

    private void bt_e_in_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_e_in_mActionPerformed
        // TODO add your handling code here:
        double startmeter, endmeter, meter, cm, mm;
        String ausgabe = "meter:    M:         CM:    MM:";
        startmeter = Double.parseDouble(txf_startmeter.getText());
        endmeter = Double.parseDouble(txf_endmeter.getText());

        while (startmeter <= endmeter) {

            meter = startmeter / 39.37;
            cm = startmeter *2.54;
            mm = startmeter *25.4;

            ausgabe = ausgabe + "\n" + String.format("%6.2f %8.2f %8.2f %8.2f\n", startmeter, meter, cm, mm);

            startmeter++;

        }
        txa_ausgabe.setText(ausgabe);
    }//GEN-LAST:event_bt_e_in_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_e_in_m;
    private javax.swing.JButton bt_m_in_e;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Startmeter;
    private javax.swing.JLabel lb_ueberschrift;
    private javax.swing.JTextArea txa_ausgabe;
    private javax.swing.JTextField txf_endmeter;
    private javax.swing.JTextField txf_startmeter;
    // End of variables declaration//GEN-END:variables
}
