/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.its.lf;

import javax.swing.JOptionPane;

/**
 *
 * @author lorenz
 */
public class GUI extends javax.swing.JFrame {

    Spieler spieler1 = new Spieler();
    Spieler spieler2 = new Spieler();
    Wuerfel wuerfel1 = new Wuerfel();
    Wuerfel wuerfel2 = new Wuerfel();
    private int wcounter1 = 0;
    private int wcounter2 = 0;
    boolean check = false;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_nameSpieler1 = new javax.swing.JLabel();
        lb_nameSpieler2 = new javax.swing.JLabel();
        txf_spieler1 = new javax.swing.JTextField();
        txf_spieler2 = new javax.swing.JTextField();
        bt_NamenFestlegen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bt_newgame = new javax.swing.JButton();
        bt_wurfspieler1 = new javax.swing.JButton();
        bt_wurfspieler2 = new javax.swing.JButton();
        lb_punktespieler1 = new javax.swing.JLabel();
        lb_punktespieler2 = new javax.swing.JLabel();
        lb_wuerfel2 = new javax.swing.JLabel();
        lb_wcounter1 = new javax.swing.JLabel();
        lb_wcounter2 = new javax.swing.JLabel();
        lb_wuerfel1 = new javax.swing.JLabel();
        lb_ergebnis = new javax.swing.JLabel();
        lb_info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Würfelspiel");

        jLabel2.setText("Jeder Spieler würfelt mit 2 Würfeln");

        jLabel3.setText("Gewonnen hat der spieler, der zuerst 20 Punke erreicht.");

        lb_nameSpieler1.setText("Spieler1");

        lb_nameSpieler2.setText("Spieler2");

        bt_NamenFestlegen.setText("Namen festlegen");
        bt_NamenFestlegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_NamenFestlegenActionPerformed(evt);
            }
        });

        jLabel6.setText("Punkte");

        jLabel7.setText("Würfel 1");

        jLabel8.setText("Würfel 2");

        jLabel9.setText("Punkte");

        bt_newgame.setText("Neues Spiel");
        bt_newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_newgameActionPerformed(evt);
            }
        });

        bt_wurfspieler1.setText("wurf");
        bt_wurfspieler1.setEnabled(false);
        bt_wurfspieler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_wurfspieler1ActionPerformed(evt);
            }
        });

        bt_wurfspieler2.setText("wurf");
        bt_wurfspieler2.setEnabled(false);
        bt_wurfspieler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_wurfspieler2ActionPerformed(evt);
            }
        });

        lb_punktespieler1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_punktespieler1.setText("Punkte Spieler1");
        lb_punktespieler1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_punktespieler2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lb_punktespieler2.setText("Punkte Spieler2");
        lb_punktespieler2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_wuerfel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lb_wuerfel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wuerfel2.setText("0");
        lb_wuerfel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_wcounter1.setText("x. Wurf");

        lb_wcounter2.setText("x. Wurf");

        lb_wuerfel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lb_wuerfel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_wuerfel1.setText("0");
        lb_wuerfel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lb_ergebnis.setFont(new java.awt.Font("Harrington", 0, 18)); // NOI18N
        lb_ergebnis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ergebnis.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lb_info.setForeground(new java.awt.Color(255, 0, 51));
        lb_info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_info.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lb_info.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(214, 214, 214)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_wurfspieler1)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_wcounter1)))
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_wuerfel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(bt_newgame)))
                        .addContainerGap(236, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_ergebnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_nameSpieler1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txf_spieler1)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(46, 46, 46)
                                        .addComponent(bt_NamenFestlegen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lb_punktespieler1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lb_wuerfel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(81, 81, 81))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_nameSpieler2)
                                    .addComponent(txf_spieler2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(lb_punktespieler2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_wurfspieler2)
                                        .addGap(18, 18, 18)
                                        .addComponent(lb_wcounter2))))
                            .addComponent(lb_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nameSpieler1)
                    .addComponent(lb_nameSpieler2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_spieler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txf_spieler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_NamenFestlegen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_punktespieler1)
                                    .addComponent(lb_punktespieler2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_wurfspieler1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bt_wurfspieler2)
                                        .addComponent(lb_wcounter2))
                                    .addComponent(lb_wcounter1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(lb_wuerfel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lb_info, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_ergebnis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_newgame)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lb_wuerfel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_NamenFestlegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_NamenFestlegenActionPerformed
        // TODO add your handling code here:

        spieler1.setName(txf_spieler1.getText());
        spieler2.setName(txf_spieler2.getText());
        lb_nameSpieler1.setText("Spieler 1: " + spieler1.getName());
        lb_nameSpieler2.setText("Spieler 2: " + spieler2.getName());
        bt_NamenFestlegen.setEnabled(false);
        txf_spieler1.setEnabled(false);
        txf_spieler2.setEnabled(false);
        checknames();
        if (check == true) {
            bt_wurfspieler1.setEnabled(true);
            bt_wurfspieler2.setEnabled(true);
        }


    }//GEN-LAST:event_bt_NamenFestlegenActionPerformed
    private void disablebuttons() {
        bt_wurfspieler1.setEnabled(false);
        bt_wurfspieler2.setEnabled(false);

    }

    private void resetwuerfel() {
        lb_info.setText(null);
        lb_wuerfel1.setText("0");
        lb_wuerfel2.setText("0");

    }

    private boolean checknames() {

        if (lb_nameSpieler1.getText() != "Spieler1" || lb_nameSpieler2.getText() != "Spieler2") {
            check = true;

        }
        return check;
    }

    private void bt_wurfspieler1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_wurfspieler1ActionPerformed
        // TODO add your handling code here:
        resetwuerfel();
        wuerfel1.werfen();
        lb_wuerfel1.setText(String.valueOf(wuerfel1.getZahl()));

        wuerfel2.werfen();
        lb_wuerfel2.setText(String.valueOf(wuerfel2.getZahl()));

        if (wuerfel1.getZahl() == wuerfel2.getZahl()) {
            lb_info.setText("Sie haben einen Pasch gewürfelt! und verlieren somit alle Punkte");
            spieler1.setPunkte(0);
        } else if ((wuerfel1.getZahl() + wuerfel2.getZahl()) <= 6) {

            lb_info.setText("Sie haben weniger als oder genau 6 gewürfelt! und bekommen somit keine Punkte");

        } else {
            spieler1.setPunkte(spieler1.getPunkte() + wuerfel1.getZahl() + wuerfel2.getZahl());
        }

        lb_punktespieler1.setText(String.valueOf(spieler1.getPunkte()));
        wcounter1++;
        lb_wcounter1.setText(String.valueOf(wcounter1 + ". Wurf"));

        bt_wurfspieler1.setEnabled(false);
        bt_wurfspieler2.setEnabled(true);
        if (spieler1.getPunkte() >= 20) {
            lb_ergebnis.setText(spieler1.getName() + " hat gewonnen mit " + spieler1.getPunkte() + " Punkten");
            disablebuttons();
        }
    }//GEN-LAST:event_bt_wurfspieler1ActionPerformed

    private void bt_wurfspieler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_wurfspieler2ActionPerformed
        // TODO add your handling code here:

        resetwuerfel();
        wuerfel1.werfen();
        lb_wuerfel1.setText(String.valueOf(wuerfel1.getZahl()));

        wuerfel2.werfen();
        lb_wuerfel2.setText(String.valueOf(wuerfel2.getZahl()));

        if (wuerfel1.getZahl() == wuerfel2.getZahl()) {
            lb_info.setText("Sie haben einen Pasch gewürfelt! und verlieren somit alle Punkte");
            spieler2.setPunkte(0);
        } else if ((wuerfel1.getZahl() + wuerfel2.getZahl()) <= 6) {
            lb_info.setText("Sie haben weniger als oder genau 6 gewürfelt! und bekommen somit keine Punkte");

        } else {

            spieler2.setPunkte(spieler2.getPunkte() + wuerfel1.getZahl() + wuerfel2.getZahl());
        }

        lb_punktespieler2.setText(String.valueOf(spieler2.getPunkte()));
        wcounter2++;
        lb_wcounter2.setText(String.valueOf(wcounter2 + ". Wurf"));

        bt_wurfspieler1.setEnabled(true);
        bt_wurfspieler2.setEnabled(false);
        if (spieler2.getPunkte() >= 20) {
            lb_ergebnis.setText(spieler2.getName() + " hat gewonnen mit " + spieler2.getPunkte() + " Punkten");
            disablebuttons();
        }

    }//GEN-LAST:event_bt_wurfspieler2ActionPerformed

    private void bt_newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_newgameActionPerformed
        // TODO add your handling code here:
        spieler1.setPunkte(0);
        spieler2.setPunkte(0);
        lb_ergebnis.setText(null);
        lb_punktespieler1.setText("Punktestand Spieler1");
        lb_punktespieler2.setText("Punktestand spieler2");
        lb_wcounter1.setText("x. Wurf");
        lb_wcounter2.setText("x. Wurf");
        wcounter1 = 0;
        wcounter2 = 0;
        lb_wuerfel1.setText("0");
        lb_wuerfel2.setText("0");
        bt_wurfspieler1.setEnabled(true);
        bt_wurfspieler2.setEnabled(true);


    }//GEN-LAST:event_bt_newgameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_NamenFestlegen;
    private javax.swing.JButton bt_newgame;
    private javax.swing.JButton bt_wurfspieler1;
    private javax.swing.JButton bt_wurfspieler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lb_ergebnis;
    private javax.swing.JLabel lb_info;
    private javax.swing.JLabel lb_nameSpieler1;
    private javax.swing.JLabel lb_nameSpieler2;
    private javax.swing.JLabel lb_punktespieler1;
    private javax.swing.JLabel lb_punktespieler2;
    private javax.swing.JLabel lb_wcounter1;
    private javax.swing.JLabel lb_wcounter2;
    private javax.swing.JLabel lb_wuerfel1;
    private javax.swing.JLabel lb_wuerfel2;
    private javax.swing.JTextField txf_spieler1;
    private javax.swing.JTextField txf_spieler2;
    // End of variables declaration//GEN-END:variables
}
