/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.its.lf;

/**
 *
 * @author lorenz
 */
public class gui_main extends javax.swing.JFrame {

    /**
     * Creates new form gui_main
     */
    public gui_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txf_Summand1 = new javax.swing.JTextField();
        txf_Summand2 = new javax.swing.JTextField();
        bt_addiere = new javax.swing.JButton();
        lb_ergebnis = new javax.swing.JLabel();
        lb_taschenrechner = new javax.swing.JLabel();
        lb_infotext = new javax.swing.JLabel();
        txf_operator = new javax.swing.JTextField();
        lb_zahl1 = new javax.swing.JLabel();
        lb_zahl2 = new javax.swing.JLabel();
        lb_operator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txf_Summand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_Summand1ActionPerformed(evt);
            }
        });

        txf_Summand2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_Summand2ActionPerformed(evt);
            }
        });

        bt_addiere.setText("Addiere");
        bt_addiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addiereActionPerformed(evt);
            }
        });

        lb_ergebnis.setText("Summe");

        lb_taschenrechner.setText("Taschenrechner");

        lb_infotext.setText("Das Ergebnis ist:");

        txf_operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txf_operatorActionPerformed(evt);
            }
        });

        lb_zahl1.setText("1. Zahl");

        lb_zahl2.setText("2. Zahl");

        lb_operator.setText("Operator + - * / ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ergebnis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_zahl1)
                            .addComponent(lb_zahl2)
                            .addComponent(lb_operator))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txf_Summand1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(txf_Summand2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txf_operator, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_taschenrechner)
                            .addComponent(bt_addiere)
                            .addComponent(lb_infotext))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_taschenrechner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Summand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_zahl1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_Summand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_zahl2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txf_operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_operator))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_addiere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_infotext)
                .addGap(18, 18, 18)
                .addComponent(lb_ergebnis)
                .addGap(82, 82, 82))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txf_Summand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_Summand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_Summand1ActionPerformed

    private void bt_addiereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addiereActionPerformed
        double summand1;
        double summand2;
        String operator;
        double ergebnis=0;

        summand1 = Double.parseDouble(txf_Summand1.getText());
        summand2 = Double.parseDouble(txf_Summand2.getText());
        operator = txf_operator.getText();

        switch (operator) {
            case "+":
                ergebnis = summand1 + summand2;
                break;
            case "-":
                ergebnis = summand1 - summand2;
                break;
            case "*":
                ergebnis = summand1 * summand2;
                break;
            case "/":
                ergebnis = summand1 / summand2;
                break;
            default:
                break;
        }

        lb_ergebnis.setText(Double.toString(ergebnis));
    }//GEN-LAST:event_bt_addiereActionPerformed

    private void txf_operatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_operatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_operatorActionPerformed

    private void txf_Summand2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txf_Summand2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txf_Summand2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_addiere;
    private javax.swing.JLabel lb_ergebnis;
    private javax.swing.JLabel lb_infotext;
    private javax.swing.JLabel lb_operator;
    private javax.swing.JLabel lb_taschenrechner;
    private javax.swing.JLabel lb_zahl1;
    private javax.swing.JLabel lb_zahl2;
    private javax.swing.JTextField txf_Summand1;
    private javax.swing.JTextField txf_Summand2;
    private javax.swing.JTextField txf_operator;
    // End of variables declaration//GEN-END:variables
}
